### ISSUE TITLE
Create Typography Component

### ISSUE THREAD

**Issue by ahmedkhitaby** [m3ntorship/m3ntorship-ui#17]
**Story**
Create a `Typography` component to use it in our projects.

**Prerequisites**
Finishing our Tailwind configurations and our library setup.

**Tasks**
Create a `Typography` component that:
- [x] Takes a text as its children
- [x] Changing the text font size, weight, line height, etc. using a `variant = "hero", "h1", "h2",....` prop. you can find these variants from [here](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=21%3A6327)
- [x] className prop to pass styles to that component 
- [x] Any other prop we might need to use it in our applications for example `align="left","right","center"...` prop.

**Acceptance criteria**
The final result should match [this](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=21%3A6327) Figma design  
![image](https://user-images.githubusercontent.com/52051312/173593922-d2b78c9d-dc73-424b-a557-278ca8bac5a1.png)

- storybook should be a guide for new developers or developers who will use the library in the future. 
- As a reader I should understand why we created the component  the use cases, how to use it,  details about the props, listing the cases that covered by the components  and any other useful info.
