### ISSUE TITLE
Create a Button Component

### ISSUE THREAD

**Issue by ahmedkhitaby** [m3ntorship/m3ntorship-ui#18]
**Story**
Create a `Button` component to use it in our projects.

**Prerequisites**
- Finishing our Tailwind configurations and our library setup.
- Transforming our Icons from SVG into Fonts.
- The Base component that will be used to build that component must be ready. this base component doesn't have any text coloring or background styling and you can find it [here](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=47%3A4242)

**Tasks**
Create a `Button` component that:
- [ ] Takes a text as its children.
- [ ] Changing the button size. using a `size = "small", "medium", "large",....` prop. you can find these sizes from [here](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=47%3A4245)
- [ ] className prop to pass styles to that component 
- [ ] Any other prop we might need to use it in our applications for example `startIcon={<DeleteIcon />`, `variant="Filled", "Ghost",...` props.

**Acceptance criteria**
The final result should match [this](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=47%3A4245) Figma design

**Comment by Nilegfx** [comment]
thanks for the nice description. I can clearly see the effort invested to increase our ticket quality. 👍

one remark:
we should also explain the base button responsibility and how it plays a key role in  the component (referring to what mostafa mentioned in his demo)

**Comment by Nilegfx** [comment]
thanks for the nice description. I can clearly see the effort invested to increase our ticket quality. 👍

one remark:
we should also explain the base button responsibility and how it plays a key role in  the component (referring to what mostafa mentioned in his demo)

**Comment by ahmedkhitaby** [comment]
@Nilegfx 

> thanks for the nice description. I can clearly see the effort invested to increase our ticket quality. +1
> 
> one remark: we should also explain the base button responsibility and how it plays a key role in the component (referring to what Mostafa mentioned in his demo)

I added the Base component as a prerequisite until we arrange with @elhaw if these base components should have a separate folder or it will be in the same file as the styled component:
- For example, the `Button.tsx` will contain both ButtonBase and Button components.

and according to that, we will decide if it is going to have a separate ticket or not.
