### ISSUE TITLE
Create IconButton Component

### ISSUE THREAD

**Issue by ahmedkhitaby** [m3ntorship/m3ntorship-ui#19]
**Story**
Create an `IconButton` component to use it in our projects.

**Prerequisites**
- Finishing our Tailwind configurations and our library setup.
- Transforming our Icons from SVG into Fonts.
- The Base component that will be used to build that component must be ready. this base component doesn't have any text coloring or background styling and you can find it [here](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=51%3A29391)

**Tasks**
Create a `IconButton` component that:
- [x] Takes a node as its children that represents the icon to display.
- [x] Changing the button size. using a `size = "small", "medium", "large",....` prop. you can find these sizes from [here](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=51%3A29389)
- [x] className prop to pass styles to that component 
- [x] Any other prop we might need to use it in our applications for example `variant="Filled", "Ghost",...` prop.

**Acceptance criteria**
The final result should match [this](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=51%3A29389) Figma design
