### ISSUE TITLE
Create full project setup

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/m3ntorship-ui#2]
**Story**
- add the initial setup/configs on top of `tsdx` initial setup

**Prerequisites**
- install `tsdx` boilerplate on your machine and start editing the initial setup  

**Tasks**
- [x] install eslint recommended plugins and integrate them with the initial eslint configs
- [ ] investigate the initial config for jest and RTL in [TSDX source code](https://github.com/jaredpalmer/tsdx) and add/remove anything if needed
- [x] upgrade husky 
- [x] install lint-staged & commitlint and integrate them with husky
- [x] remove all node versions before `v14` in `main.yaml`
- [x] add coverage folder to `.gitignore`

**Acceptance criteria**
the project should run properly on all operating systems after finishing the installation process

**Comment by saifaldin** [comment]
@AhmedAdel999 Please add description
