### ISSUE TITLE
fix eslint formatting & configs

### ISSUE THREAD

**Issue by atwfk** [m3ntorship/m3ntorship-ui#21]
**Story**
- fix eslint formatting & configs

**Prerequisites**
- when editing project files and saving the changes, `eslint-plugin-prettier` wasn't formatting any files on saving
- eslint extension was showing some errors which tsdx was ignoring them on pre-commit

**Tasks**
- [ ] add eslint configs in vscode settings file to format on save but eslint defined rules
- [ ] remove `eslint-plugin-tsc` and add script for typechecking typescript errors
- [ ] automate running typecheck script

**Acceptance criteria**
- eslint should be configured properly
- files should be formatted on save
- typecheck should be added on pre-commit
