### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/m3ntorship-ui#3]
**Story**
Dockerize our component library using docker to unify the Development environment and Deploy our storybook.

**Tasks**
- both of these tasks should be applied for development and production scenarios :
  - [x] Create a `Dockerfile` that can be used to build our image.
  - [x] Create a `.dockerignore` file to exclude `node_modules`, and unneeded files that are going to increase our image size
  - [x] Create a `docker-compose.yml` file that contains the written instructions to manage our containers

**Acceptance criteria**
Creating these files and using docker-compose commands to make our container up and running easily

**Comment by ahmedkhitaby** [comment]
@elhaw  I have added these files for our development environment.
For the production environment, I know the configurations for both Dockerfile and docker-compose but couldn't test it without a `VPS`

**Comment by ahmedkhitaby** [comment]
@elhaw after my meeting with Mr. Ayoub and @ahmedelsayad11 we agreed that there is no need for VPS and `Dockerfile` is the only file we are going to use to deploy our storybook in Heroku after building our project using Github actions.
