### ISSUE TITLE
Create Link component

### ISSUE THREAD

**Issue by ahmedkhitaby** [m3ntorship/m3ntorship-ui#30]
**Story**
Create a `Link` component to use it in our projects.

**Tasks**
Create a `Link` component that:
- [x] Takes a text or a node as its children
- [x] Takes a `href` prop that refers to a specific link.
- [x] Changing the text font size, weight, line height, etc. using a `size = "default", "small",....` prop. you can find these values from [here](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=51%3A6030)
- [x] className prop to pass styles to that component or any other prop we might need to use

**Acceptance criteria**
The final result should match [this](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=51%3A6030) Figma design  
![image](https://user-images.githubusercontent.com/52051312/174873766-529f7d46-a7f0-4b88-bc4d-4d6734f0a407.png)
