### ISSUE TITLE
Create Text Input Component

### ISSUE THREAD

**Issue by Ali-Khamis** [m3ntorship/m3ntorship-ui#44]
**Story**
Create a `Text Input` component to use in our projects.

**Prerequisites**

- Transforming our Icons from SVG into Fonts.
- The Base component that will be used to build this component must match the [Figma design](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=59%3A3539).

**Tasks**
Create a `Text Input` component that:

- [ ] Take placeholder as a prop
- [ ] ClassName prop to pass styles to that component
- [ ] To have onChange prop to watch the input value change
- [ ] To have varients and colors needed based on the [Figma design](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=61%3A5694).

**Acceptance criteria**
The final result should match [Figma design](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=61%3A5694).
