### ISSUE TITLE
edit README.md file and add the project details

### ISSUE THREAD

**Issue by atwfk** [m3ntorship/m3ntorship-ui#7]
**Tasks**
- [ ] add the tech stack which m3ntorship-ui is using
- [ ] add prerequisites for running the project locally on any machine
- [ ] explain the scripts which used in the project
- [ ] add the project/folders structure

**Acceptance criteria**
the description should be simple enough for anyone wants to contribute in m3ntorship-ui
